# -*- mode: ruby -*-
# vi: set ft=ruby :

user = "vadmin"

Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/9"
  config.vm.hostname = "mshasal9test01"
  config.vm.box_check_update = false
  config.vm.network "public_network", bridge: "External", ip: "192.168.50.20", auto_config: true
  # config.vm.network "private_network", bridge: "Internal", ip: "192.168.80.3" ###Internal Network
  # config.vm.network "forwarded_port", guest: 80, host: 80
  # config.vm.network "forwarded_port", guest: 443, host: 443 
  # config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provider "hyperv" do |h|
    h.enable_virtualization_extensions = false
    h.linked_clone = true
    h.memory = 2048
    h.cpus = 2
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "shell", inline: <<-SHELL
    export LANGUAGE=en_US.UTF-8
    export LANG=en_US.UTF-8
    export LC_ALL=en_US.UTF-8

    sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
    sudo echo LANG=en_US.utf-8 >> /etc/environment
    sudo echo LC_ALL=en_US.utf-8 >> /etc/environment

    sudo rm /etc/localtime
    sudo timedatectl set-timezone Europe/Warsaw

    sudo dnf update -y
    sudo dnf install gcc make perl -y
    sudo dnf install kernel-devel -y
    sudo dnf install epel-release -y
  SHELL

  # config.vm.provision "file", source: "id_rsa.pub", destination: "/tmp/key"

  # config.vm.provision "shell", run: "once", privileged: true, inline: <<-SHELL
  #   sudo useradd -m -s /bin/bash -U #{user}
  #   sudo mkdir -p /home/#{user}/.ssh
  #   sudo mv /tmp/key /home/#{user}/.ssh/authorized_keys
  #   sudo chown -R #{user}:#{user} /home/#{user}
  #   sudo chmod -R 600 /home/#{user}/.ssh/authorized_keys
  #   sudo su
  #   echo "%#{user} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/#{user}
  #   exit
  # SHELL

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
