# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  config.vm.hostname = "mshasd10test01"
  config.vm.provider "hyperv"
  config.vm.network "public_network", bridge: "External", ip: "192.168.50.23", auto_config: true

#  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  config.vm.provider "hyperv" do |h|
    h.enable_virtualization_extensions = false
    h.linked_clone = true
    h.memory = 1024
    h.cpus = 2
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive

    sudo apt-get update
    sudo apt-get -y upgrade

    export LANGUAGE=en_US.UTF-8
    export LANG=en_US.UTF-8
    export LC_ALL=en_US.UTF-8
    sudo apt-get install -y \
        gcc \
        make \
        curl \
        perl
        
    sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
  SHELL

  config.vm.post_up_message = <<-EOT
    Hello - your VM is up !
  EOT

end
